
logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    ru.denumtech: ${LOG_LEVEL_RU:debug}

spring:
  application:
    name: javapro
  main:
    allow-bean-definition-overriding: true
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
    rabbitmq:
      listener:
        direct:
          auto-startup: false