logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}

spring:
  application:
    name: javapro
  main:
    allow-bean-definition-overriding: true
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
    rabbitmq:
      listener:
        direct:
          auto-startup: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
    database-change-log-table: changelog
    database-change-log-lock-table: changeloglock
    default-schema: public
    liquibase-schema: public



  datasource:
      jdbc-url: jdbc:postgresql://${DB_HOST:192.168.1.90:32768}/${DB_NAME:test}?prepareThreshold=0
      username: postgres
      password: postgres
      driverClassName: org.postgresql.Driver
